const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const calls=[];class Storage {constructor(){this.map=new Map()}setItem(k,v){this.map.set(k,String(v))}getItem(k){return this.map.get(k)||null}removeItem(k){this.map.delete(k)}}const localStorage=new Storage(),window={__nativePreferences:{'workstation-api-base':'https://example.com/v1'},webkit:{messageHandlers:{desktop:{postMessage:async b=>{calls.push(b);return {ok:true}}}}}};vm.runInNewContext(fs.readFileSync('native/Resources/desktop.js','utf8'),{window,Storage,localStorage});return {window,localStorage,calls};}
test('native settings survive backend origin changes through initial preferences',()=>{const x=setup();assert.equal(x.localStorage.getItem('workstation-api-base'),'https://example.com/v1');assert.equal(x.calls.length,0)});
test('credential IPC uses separate namespaces and returns a promise',async()=>{const x=setup();await x.window.workstationDesktop.embeddingCredentials.read({base:'https://example.com/v1'});assert.equal(x.calls[0].channel,'embedding');assert.equal(x.calls[0].action,'read')});
test('native file storage capability and reentry errors reach both settings channels without a secret or extra request',async()=>{const x=setup();for(const channel of ['apiCredentials','embeddingCredentials']){assert.equal(x.window.workstationDesktop[channel].storageBackend,'encrypted-file');x.window.webkit.messageHandlers.desktop.postMessage=async()=>{throw Error('[CREDENTIAL_REENTRY_REQUIRED] Paste your Key again');};await assert.rejects(x.window.workstationDesktop[channel].read({base:'https://example.invalid/v1'}),e=>e.code==='CREDENTIAL_REENTRY_REQUIRED'&&e.message==='Paste your Key again');}assert.equal(x.calls.length,0);});
test('native vectors use a workspace store across changing browser origins',async()=>{const x=setup(),s=x.window.workstationDesktop.vectorIndex;await s.write('profile',[{id:'row'}],['old']);await s.load('profile');assert.equal(x.calls[0].command,'vector-index');assert.equal(x.calls[0].action,'write');assert.deepEqual(x.calls[0].removes,['old']);assert.equal(x.calls[1].action,'load');});
test('only preference allowlist persists; keys and workspace content never enter it',()=>{const x=setup();x.localStorage.setItem('workstation-api-key','synthetic');x.localStorage.setItem('workstation-state','private fixture');assert.equal(x.calls.length,0);x.localStorage.setItem('workstation-provider','openai-auth');assert.equal(x.calls[0].key,'workstation-provider');x.localStorage.removeItem('workstation-provider');assert.equal(x.calls[1].value,undefined)});

test('explicit credential authorization is distinct from automatic reads and saves',async()=>{const x=setup(),a=x.window.workstationDesktop.apiCredentials,e=x.window.workstationDesktop.embeddingCredentials;await a.unlock({base:'https://example.invalid/v1'});await a.authorizeSave({base:'https://example.invalid/v1',token:'synthetic'});await e.authorizeRemove();await e.read({base:'https://example.invalid/v1'});assert.deepEqual(x.calls.map(c=>[c.channel,c.action]),[['api','unlock'],['api','authorizeSave'],['embedding','authorizeRemove'],['embedding','read']]);});
test('native credential errors preserve lock and cancellation codes without exposing transport markers',async()=>{const x=setup();x.window.webkit.messageHandlers.desktop.postMessage=async()=>{throw Error('[KEYCHAIN_LOCKED] Open settings to unlock');};await assert.rejects(x.window.workstationDesktop.apiCredentials.read({base:'https://example.invalid/v1'}),e=>e.code==='KEYCHAIN_LOCKED'&&e.message==='Open settings to unlock');x.window.webkit.messageHandlers.desktop.postMessage=async()=>{throw Error('[KEYCHAIN_CANCELLED] Cancelled');};await assert.rejects(x.window.workstationDesktop.embeddingCredentials.unlock({base:'https://example.invalid/v1'}),e=>e.code==='KEYCHAIN_CANCELLED');});
