const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../app/pdf-search');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
const hit=(y=20)=>({rects:[{x:10,y,width:40,height:12,angle:0}]});
const response=(page,overrides={})=>({ok:true,json:async()=>({page,pageCount:3,width:612,height:792,matches:[hit()],...overrides})});
function harness(custom={}){const requests=[],updates=[],selected=[],timers=new Map();let id=0,allowed=true;const api=create({base:'/__files/fixture',getPageCount:()=>3,getPage:()=>2,onValid:()=>allowed,fetch:async(url,init)=>{requests.push({url,init});return response(Number(new URL(url,'http://fixture').searchParams.get('page')));},setTimeout:fn=>{timers.set(++id,fn);return id;},clearTimeout:id=>timers.delete(id),onUpdate:value=>updates.push(value),onMatch:hit=>selected.push(hit),...custom});return {api,requests,updates,selected,timers,set allowed(value){allowed=value;},fire(){const work=[...timers];timers.clear();for(const[,fn]of work)fn();}};}
test('opening alone does not extract text; rapid typing debounces and queries stay local',async()=>{const h=harness();h.api.open();assert.equal(h.requests.length,0);h.api.query('first');h.api.query('a & 中');assert.equal(h.timers.size,1);assert.equal(h.requests.length,0);h.fire();await tick();assert.equal(h.requests.length,3);assert.ok(h.requests.every(r=>r.url.startsWith('/__files/fixture/preview-search?')));assert.ok(h.requests.every(r=>new URL(r.url,'http://fixture').searchParams.get('q')==='a & 中'));});
test('progress scans one page at a time starting at the current page and never claims a full total early',async()=>{const gates=[deferred(),deferred(),deferred()],calls=[];const h=harness({fetch:(url,init)=>{calls.push({url,init});return gates[calls.length-1].promise;}});h.api.query('word');const done=h.api.run();assert.equal(calls.length,1);gates[0].resolve(response(2));await tick();assert.equal(calls.length,2);assert.equal(h.api.snapshot().phase,'scanning');assert.equal(h.api.snapshot().scanned,1);assert.equal(h.selected[0].page,2);gates[1].resolve(response(3));await tick();gates[2].resolve(response(1));await done;assert.deepEqual(h.api.snapshot().matches.map(h=>h.page),[2,3,1]);assert.equal(h.api.snapshot().phase,'done');assert.equal(h.api.snapshot().scanned,3);});
test('navigation wraps verified matches in scan order and retains one logical multiline hit',async()=>{const h=harness({fetch:async url=>response(Number(new URL(url,'http://fixture').searchParams.get('page')),{matches:[{rects:[hit().rects[0],hit(40).rects[0]]}]})});h.api.query('phrase');await h.api.run();assert.equal(h.api.snapshot().matches.length,3);assert.equal(h.api.snapshot().matches[0].rects.length,2);h.api.move(-1);assert.equal(h.selected.at(-1).page,1);h.api.move(1);assert.equal(h.selected.at(-1).page,2);});
test('changing a query aborts and ignores the late prior response',async()=>{const gate=deferred(),calls=[];const h=harness({fetch:(url,init)=>{calls.push({url,init});return gate.promise;}});h.api.query('old');const done=h.api.run();h.api.query('new');assert.equal(calls[0].init.signal.aborted,true);gate.resolve(response(2));await done;assert.equal(h.api.snapshot().matches.length,0);assert.equal(h.api.snapshot().query,'new');assert.equal(calls.length,1);});
test('close, clear, destroy and access revocation prevent late results and further requests',async()=>{for(const action of['close','clear','destroy','revoke']){const gate=deferred(),calls=[];const h=harness({fetch:(url,init)=>{calls.push({url,init});return gate.promise;}});h.api.query('word');const done=h.api.run();if(action==='clear')h.api.query('');else if(action==='revoke')h.allowed=false;else h.api[action]();gate.resolve(response(2));await done;assert.equal(calls.length,1);assert.equal(h.api.snapshot().matches.length,0);assert.equal(h.selected.length,0);assert.equal(calls[0].init.signal.aborted,true);}});
test('stop retains verified hits but cancels the next page, and restart is explicit',async()=>{const gate=deferred(),calls=[];const h=harness({fetch:(url,init)=>{calls.push({url,init});return calls.length===1?Promise.resolve(response(2)):gate.promise;}});h.api.query('word');const done=h.api.run();await tick();h.api.stop();assert.equal(h.api.snapshot().phase,'stopped');assert.equal(h.api.snapshot().scanned,1);assert.equal(h.api.snapshot().matches.length,1);assert.equal(calls[1].init.signal.aborted,true);gate.resolve(response(3));await done;assert.equal(calls.length,2);h.api.move(1);assert.equal(h.selected.at(-1).page,2);assert.equal(calls.length,2);});
test('response failures retain already verified hits with literal actionable error',async()=>{let n=0;const h=harness({fetch:async()=>++n===1?response(2):{ok:false,status:403,json:async()=>({error:'Copy restricted <text>'})}});h.api.query('word');await h.api.run();assert.equal(h.api.snapshot().phase,'error');assert.equal(h.api.snapshot().matches.length,1);assert.equal(h.api.snapshot().error,'Copy restricted <text>');assert.equal(n,2);});
test('scanned/partial/truncated pages are counted as incomplete, never an unqualified no-match',async()=>{let n=0;const h=harness({fetch:async url=>response(Number(new URL(url,'http://fixture').searchParams.get('page')),{matches:[],...[{unsearchable:true},{partial:true},{truncated:true}][n++]})});h.api.query('word');await h.api.run();assert.equal(h.api.snapshot().phase,'done');assert.equal(h.api.snapshot().incomplete,3);assert.equal(h.api.snapshot().matches.length,0);});
test('overall cap prevents unbounded retained hits or further page scans',async()=>{const h=harness({limit:2});h.api.query('word');await h.api.run();assert.equal(h.api.snapshot().matches.length,2);assert.equal(h.api.snapshot().capped,true);assert.equal(h.api.snapshot().scanned,2);assert.equal(h.requests.length,2);});
test('malformed geometry/page identity fails before highlight publication',async()=>{for(const bad of[{page:1},{width:NaN},{pageCount:4},{matches:[{rects:[]}]},{matches:[{rects:[{x:0,y:1,width:3,height:4,angle:45}]}]}]){const h=harness({fetch:async()=>response(2,bad)});h.api.query('word');await h.api.run();assert.equal(h.api.snapshot().phase,'error');assert.equal(h.selected.length,0);}});
test('empty or overlong queries never request pages; Unicode count uses code points',async()=>{const h=harness();h.api.query(' ');h.fire();assert.equal(h.requests.length,0);h.api.query('x'.repeat(257));await h.api.run();assert.equal(h.api.snapshot().phase,'invalid');assert.equal(h.requests.length,0);h.api.query('𠮷'.repeat(256));await h.api.run();assert.equal(h.requests.length,3);});
