// English fictional data for the English ScreenCam recording.
// Append after qa-workspace.js and workspace.js, only in an isolated QA bundle.
(()=>{
 const now=Date.now();
 const projectNames={'native-qa':'Video understanding · Research','qa-course':'Linear algebra · Study notes','qa-trip':'Autumn trail weekend','qa-wellness':'Build a steady routine','qa-home':'A more organized home'};
 state.projects.forEach(p=>{p.name=projectNames[p.id]||p.name;p.description=p.id==='native-qa'?'Study how sampling changes short-event coverage. Keep evidence, failed attempts and the next experiment.':'';});
 const tasks=['Choose a trail','Plan the journey','Book a weekend stay','Pack light','Check weather and a backup route','Plan a weekly routine','Complete an easy run','Finish a stretching session','Keep a regular sleep schedule','Prepare a weekend ride','Book a fitness check','Clear the desk and cables','Sort unused items','Donate useful books','Organize digital documents','Update the home inventory'];
 state.tasks.forEach((t,i)=>{t.title=tasks[i]||'Example task';t.description='A fictional task in an isolated demonstration workspace.';});
 const wiki=[
 ['concept','Temporal sampling and event coverage','## Definition and scope\nSampling turns a continuous timeline into a finite set of observations. The sampling interval and event duration jointly affect coverage.\n\n## Related concepts\nObserving an event does not mean a model can explain it. Track coverage and answer accuracy separately.\n\n## Next step\nCompare uniform and adaptive sampling.'],
 ['method','Adaptive keyframe sampling','## Core idea\nStart with a coarse scan, then add observations around larger changes.\n\n## Assumptions\nA fixed compute budget and identifiable candidate segments.\n\n## Limitations\nSlow but important changes can still be missed.\n\n## Procedure\n1. Establish a fixed-budget baseline.\n2. Add samples around candidate changes.\n3. Evaluate the short-event subset separately.'],
 ['experiment','Experiment 01 · Short-event coverage','## Hypothesis\nAdaptive sampling may improve short-event coverage with the same frame budget.\n\n## Controls\nHold the model, prompt and frame count constant.\n\n## Results\nThis fictional experiment is planned, not executed. A hypothesis is not a result.\n\n## Next step\nPrepare a small annotated short-event subset.'],
 ['failure','When uniform sampling misses short events','## Symptom\nCoarse sampling can skip a short action entirely.\n\n## Observation\nThis is a fictional failure record for demonstrating research structure. There are no measured results.\n\n## Boundary\nInspect events shorter than the sampling interval first.'],
 ['review','Review · Comparable evaluation','## Feedback\nExample feedback: compare methods under the same compute budget.\n\n## Response\nFix the input frame count. Report the full set and short-event subset separately.\n\n## Status\nTo be verified.'],
 ['idea','Can we learn where to spend the frame budget?','## Question\nCan coarse observations predict where denser sampling is useful?\n\n## Hypothesis\nVerify improved coverage before attempting end-to-end learning.\n\n## Next step\nStart with a small controlled comparison and keep the failure cases.']];
 state.notes=wiki.map(([type,title,body])=>({id:'demo-wiki-'+type,title,content:'# '+title+'\n\n'+body,kind:'科研 Wiki/'+type,workspace:'科研',projectId:'native-qa',createdAt:now,updatedAt:now,sourceAttachmentIds:[],tags:['Video understanding','Sampling']}));
 state.notes.push({id:'qa-note-trip',title:'Trail weekend · Field notes',kind:'note',workspace:'日常',projectId:'qa-trip',content:'# Trail weekend · Field notes\n\n> Leave some room in the plan.\n\n## Itinerary\n\n| Day | Plan | Note |\n| --- | --- | --- |\n| Saturday morning | Travel and a short walk | Check the weather |\n| Saturday afternoon | Explore the trail | Allow time to rest |\n| Sunday | Return home | Keep it flexible |\n\n## Packing\n- [x] Light backpack\n- [ ] Rain gear\n- [ ] Water and snacks\n\n## To confirm\nAccommodation cancellation terms and transport times.',createdAt:now,updatedAt:now,sourceAttachmentIds:[]});
 ['A useful control: change only the sampling strategy.','Average accuracy may hide failures on short events.','Compare both strategies in the next discussion and keep the open questions.'].forEach((text,i)=>state.notes.push({id:'demo-capture-'+i,title:text,content:text,kind:'随记',workspace:'科研',projectId:'native-qa',tags:['Experiment idea'],createdAt:now-i*3600000,updatedAt:now,sourceAttachmentIds:[]}));
 const chat=state.conversations[0];Object.assign(chat,{title:'Prepare a trail weekend',name:'Prepare a trail weekend',workspace:'日常',projectId:'qa-trip',messages:[],modelConfig:{provider:'api',model:'Demo preset',effort:''}});
 const run={id:'demo-review-en',conversationId:chat.id,workspace:'日常',projectId:'qa-trip',goal:'Organize our trip preparation into an editable checklist.',steps:[],status:'completed',createdAt:now,completedAt:now,model:'Demo preset'};
 state.agentRuns=[run];
 const results=executeActions([{type:'create_note',title:'Trip preparation checklist',content:'# Trip preparation checklist\n\n> Make space for a calm departure.\n\n## Before leaving\n- Confirm transport and accommodation\n- Check the latest weather\n- Share the route with the group\n\n## Pack light\n- Water, snacks and rain gear\n- A power bank and offline maps\n\n## Backup plan\nAdjust the route if the weather changes. There is no need to rush.',workspace:'日常',projectId:'qa-trip',sourceAttachmentIds:[]}],run);
 chat.messages=[{id:'demo-ask-en',role:'user',text:run.goal},{id:'demo-reply-en',role:'assistant',text:'The trip preparation checklist is ready. Open the reading pane to review the new content, then keep refining it.',runId:run.id,results}];
 state.currentConversationId=chat.id;normalizeStateShape(state);save();window.WorkstationI18n.setLanguage('en');renderAll();return true;
})();
