import React from 'react';
import { Badge, Button, Caption, EmptyState, Heading } from './halaska-kit.jsx';
const t = (zh, en) => /^en(?:-|$)/i.test(document.documentElement.lang || '') ? en : zh;
const labels = () => ({ approval: t('确认请求', 'Approval requests'), completed: t('已完成', 'Completed'), failed: t('失败与中断', 'Failed / interrupted'), stopped: t('已停止', 'Stopped') });
const objectLabels = () => ({ task: t('任务', 'tasks'), note: t('笔记', 'notes'), import: t('资料', 'materials'), paper: t('论文', 'papers'), project: t('项目', 'projects') });
function Bell({ size = 18 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg>; }
function dateLabel(at) {
  const date = new Date(at), today = new Date(), yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1);
  if (date.toDateString() === today.toDateString()) return t('今天', 'Today');
  if (date.toDateString() === yesterday.toDateString()) return t('昨天', 'Yesterday');
  return date.toLocaleDateString(/^en/.test(document.documentElement.lang) ? 'en-US' : 'zh-CN', { month: 'short', day: 'numeric', year: 'numeric' });
}
export function ActivityCenterBadge({ count }) { return count > 0 ? <span className="activity-center-badge" aria-label={t(`${count} 条未读活动`, `${count} unread activities`)}>{count > 99 ? '99+' : count}</span> : null; }
export function ActivityCenterSurface({ events, total, page, pages, filters, projects, digest, unread, busy, error, notice, limited, observationLimited, source, onFilter, onPage, onRead, onArchive, onMarkFiltered, onSource, onClose }) {
  const kinds = labels(), objects = objectLabels(), groups = [];
  for (const event of events) { const label = dateLabel(event.occurredAt); const previous = groups.at(-1); if (previous?.label === label) previous.events.push(event); else groups.push({ label, events: [event] }); }
  const projectName = id => projects.find(project => project.id === id)?.name || t('未归属项目', 'No project');
  return <section className="activity-center-surface">
    <header className="activity-center-heading"><div className="activity-center-heading-icon"><Bell size={22} /></div><div><Caption>{t('你的工作区动态', 'WORKSPACE ACTIVITY')}</Caption><Heading level={2}><span id="activityCenterTitle">{t('通知与变化', 'Activity & updates')}</span></Heading></div><Badge variant={unread ? 'accent' : 'default'}>{t(`${unread} 未读`, `${unread} unread`)}</Badge><Button size="sm" variant="ghost" disabled={busy} aria-label={t('关闭通知中心', 'Close activity center')} onClick={onClose}>✕</Button></header>
    <section className="activity-center-digest" aria-label={t('自上次查看以来', 'Since your last visit')}><div className="activity-center-digest-title"><span>{t('自上次查看', 'Since your last visit')}</span><strong>{digest.total ? t(`${digest.total} 条变化`, `${digest.total} updates`) : t('没有新的变化', 'No new updates')}</strong></div>
      {!!digest.total && <div className="activity-center-digest-counts">{Object.entries(digest.counts).filter(([, count]) => count > 0).map(([kind, count]) => <Button key={kind} size="sm" variant="ghost" aria-pressed={filters.kind === kind} onClick={() => onFilter('kind', filters.kind === kind ? '' : kind)}><span className={`activity-center-status-dot ${kind}`} />{kinds[kind]} <b>{count}</b></Button>)}</div>}
      {!!Object.keys(digest.changes).length && <p>{t('执行记录中涉及的变更：', 'Changes recorded by runs: ')}{Object.entries(digest.changes).map(([kind, count]) => `${count} ${objects[kind] || kind}`).join(' · ')}</p>}
      <p>{digest.truncated ? t('部分较早动态已超过保留上限，下方摘要仅统计仍保留的记录。', 'Some older activity exceeded retention. This summary counts retained records only.') : t('来自实际执行记录；查看摘要不会将通知标为已读。', 'Based on recorded runs. Viewing this summary does not mark notifications as read.')}</p>
    </section>
    <div className="activity-center-toolbar"><div className="activity-center-segments" role="group" aria-label={t('活动范围', 'Activity scope')}><Button size="sm" variant={filters.archived ? 'ghost' : 'secondary'} aria-pressed={!filters.archived} onClick={() => onFilter('archived', false)}>{t('收件箱', 'Inbox')}</Button><Button size="sm" variant={filters.archived ? 'secondary' : 'ghost'} aria-pressed={!!filters.archived} onClick={() => onFilter('archived', true)}>{t('已归档', 'Archived')}</Button></div><Button size="sm" variant="ghost" disabled={busy || !total} onClick={onMarkFiltered}>{t('将筛选结果标为已读', 'Mark filtered as read')}</Button></div>
    <div className="activity-center-filters"><label><span>{t('项目', 'Project')}</span><select aria-label={t('按项目筛选', 'Filter by project')} value={filters.projectId} onChange={event => onFilter('projectId', event.target.value)}><option value="">{t('所有项目', 'All projects')}</option><option value="__none__">{t('未归属项目', 'No project')}</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label><span>{t('类型', 'Type')}</span><select aria-label={t('按活动类型筛选', 'Filter by activity type')} value={filters.kind} onChange={event => onFilter('kind', event.target.value)}><option value="">{t('所有类型', 'All types')}</option>{Object.entries(kinds).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></label><Button size="sm" variant={filters.unread ? 'secondary' : 'ghost'} aria-pressed={!!filters.unread} onClick={() => onFilter('unread', !filters.unread)}>{t('仅未读', 'Unread only')}</Button></div>
    <div className="activity-center-feedback" aria-live="polite" role={error ? 'alert' : 'status'}>{error || (busy ? t('正在保存…', 'Saving…') : notice)}{error && <span className="activity-center-error-dot" />}</div>
    <div className="activity-center-list" tabIndex={-1} aria-label={t('活动记录', 'Activity history')}>
      {!events.length && <EmptyState icon={<Bell size={28} />} title={filters.archived ? t('归档中没有这些通知', 'No matching archived activity') : t('现在很安静', 'All quiet for now')} description={total ? '' : t('新的执行结果和待确认事项会出现在这里。首次启用时，既有历史记录不会重新通知。', 'New run results and approval requests appear here. Existing history is not replayed when first enabled.')} />}
      {groups.map((group, index) => <section className="activity-center-group" key={`${group.label}-${index}`} aria-label={group.label}><h3>{group.label}</h3>{group.events.map(event => {
        const availability = source(event), stale = availability.outdated, changes = Object.entries(event.counts || {}), status = event.status === 'interrupted' ? t('执行中断', 'Interrupted') : event.status === 'rejected' ? t('已拒绝', 'Rejected') : event.kind === 'approval' ? (stale ? t('确认已处理', 'Approval handled') : t('待确认', 'Needs approval')) : event.kind === 'failed' ? t('执行失败', 'Failed') : kinds[event.kind];
        return <article key={event.id} className={`activity-center-item ${event.readAt ? 'is-read' : 'is-unread'}`} data-activity-id={event.id}>
          <span className={`activity-center-symbol ${event.kind}`} aria-hidden="true">{event.kind === 'completed' ? '✓' : event.kind === 'approval' ? '◇' : event.kind === 'failed' ? '!' : '—'}</span>
          <div className="activity-center-item-content"><div className="activity-center-item-meta"><span className={`activity-center-state ${event.kind}`}>{status}</span><span className="activity-center-project" title={projectName(event.projectId)}>{projectName(event.projectId)}</span><time dateTime={new Date(event.occurredAt).toISOString()} title={event.timeEstimated ? t('记录捕捉时间；来源没有完成时间。', 'Time observed; the source did not record a completion time.') : new Date(event.occurredAt).toLocaleString()}>{new Date(event.occurredAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>
            <h4 title={event.title}>{event.title}</h4>
            {!!changes.length && <p className="activity-center-result-summary">{changes.map(([kind, count]) => `${count} ${objects[kind] || kind}`).join(' · ')}{t(' 有记录的变更', ' recorded changes')}</p>}
            {stale && <p className="activity-center-source-note">{t('这次确认已处理，打开对话查看当前结果。', 'This approval was already handled. Open the conversation for the current result.')}</p>}
            {!availability.available && <p className="activity-center-source-note">{availability.reason}</p>}
            {!!event.references?.length && <div className="activity-center-results">{event.references.map((reference, index) => <Button key={`${reference.kind}:${reference.id}:${index}`} size="sm" variant="ghost" disabled={busy} title={reference.title} onClick={() => onSource(event.id, index)}>{objects[reference.kind] || reference.kind} · {reference.title}</Button>)}{event.resultCount > event.references.length && <span>{t(`另有 ${event.resultCount - event.references.length} 项结果，可在对话中查看`, `${event.resultCount - event.references.length} more results in the conversation`)}</span>}</div>}
            <div className="activity-center-item-actions"><Button size="sm" variant="ghost" disabled={busy || !availability.available} onClick={() => onSource(event.id)}>{t('打开对话', 'Open conversation')} <span aria-hidden="true">↗</span></Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => onRead(event.id, !!event.readAt ? false : true)}>{event.readAt ? t('标为未读', 'Mark unread') : t('标为已读', 'Mark read')}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => onArchive(event.id, !event.archivedAt)}>{event.archivedAt ? t('恢复', 'Restore') : t('归档', 'Archive')}</Button></div>
          </div><span className="activity-center-unread-dot" aria-label={event.readAt ? t('已读', 'Read') : t('未读', 'Unread')} />
        </article>;
      })}</section>)}
    </div>
    <footer className="activity-center-footer"><span>{t(`共 ${total} 条`, `${total} activities`)}{limited ? t(' · 保留最近 300 条', ' · Latest 300 retained') : ''}</span><div><Button size="sm" variant="ghost" disabled={page <= 0} aria-label={t('上一页活动', 'Previous activity page')} onClick={() => onPage(page - 1)}>←</Button><span>{page + 1} / {pages}</span><Button size="sm" variant="ghost" disabled={page + 1 >= pages} aria-label={t('下一页活动', 'Next activity page')} onClick={() => onPage(page + 1)}>→</Button></div></footer>
    <p className="activity-center-local-note">{observationLimited ? t('执行状态跟踪已达到 5000 条上限，超出范围的旧执行将不再重新通知。', 'Run tracking reached its 5,000-record limit. Older runs outside retention will not notify again.') : t('仅此设备 · 不包含无痕会话 · 原始对话与结果不受已读和归档操作影响', 'This device only · Private conversations excluded · Reading and archiving leave source data unchanged')}</p>
  </section>;
}
