import React, { useId, useLayoutEffect, useRef, useState } from 'react';
import { AlertBanner, Badge, Button, Caption, Card, EmptyState, Heading, StatusBadge, TextArea, TextInput } from './halaska-kit.jsx';
import { KitCheckbox, KitRadioGroup, KitSearchInput, KitSelect, KitTabs } from './kit-controls.jsx';

const t = (zh, en) => /^en(?:-|$)/i.test(document.documentElement.lang || '') ? en : zh;
const typeName = kind => ({ note: t('笔记', 'Note'), import: t('资料', 'Material'), paper: t('论文记录', 'Paper record') })[kind] || kind;
const excerptName = label => ({ 'note-content': t('已保存的笔记正文', 'Saved note text'), 'extracted-text': t('文件的已提取文本', 'Extracted file text'), 'extracted-pages': t('已提取页面文本，方括号为页码', 'Extracted pages; brackets indicate page numbers'), 'paper-record': t('已保存论文记录，可能包含既有分析', 'Saved paper record; may include earlier analysis') })[label] || t('保存的摘录', 'Saved excerpt');
const relationOptions = () => [{ value: 'unclassified', label: t('尚未分类', 'Unclassified') }, { value: 'supports', label: t('支持', 'Supports') }, { value: 'contradicts', label: t('反例 / 相反证据', 'Counterevidence') }, { value: 'related', label: t('相关背景', 'Related background') }];
const relationName = value => relationOptions().find(option => option.value === value)?.label || relationOptions()[0].label;
const statusName = value => ({ draft: t('草稿', 'Draft'), insufficient: t('证据不足', 'Insufficient evidence'), ready: t('已整理', 'Organized') })[value] || t('草稿', 'Draft');
const evidenceName = evidence => evidence?.confirmed ? t('你已复核', 'Reviewed by you') : ({ empty: t('待补原文', 'Add an excerpt'), unavailable: t('来源不可用', 'Source unavailable'), stale: t('来源已变化', 'Source changed'), unmatched: t('原文待核对', 'Check the excerpt'), unclassified: t('待分类', 'Classify evidence'), unreviewed: t('待你复核', 'Review needed') })[evidence?.status] || t('待你复核', 'Review needed');
const sourceTitle = (source, status) => status?.available && !status?.redacted ? source.title : t('来源不可用', 'Source unavailable');

// Actual Kit fields retain their nodes while host projections update. The local
// draft protects IME composition; semantic attributes fill gaps in upstream API.
export function ComparisonField({ id, value = '', onChange, label, ariaLabel, caption, placeholder, disabled = false, maxLength, rows, invalid = false, className = '' }) {
  const generated = useId(), fieldId = id || `comparison-field-${generated}`, ref = useRef(null), composing = useRef(false), lastSent = useRef(String(value));
  const [draft, setDraft] = useState(String(value));
  useLayoutEffect(() => { if (!composing.current) { setDraft(String(value)); lastSent.current = String(value); } }, [value]);
  const submit = next => { if (!disabled && next !== lastSent.current) { lastSent.current = next; onChange?.(next); } };
  useLayoutEffect(() => {
    const input = ref.current?.querySelector('input,textarea'); if (!input) return;
    input.id = fieldId; input.setAttribute('aria-label', ariaLabel || label || '');
    if (maxLength != null) input.maxLength = maxLength; else input.removeAttribute('maxlength');
    if (invalid) input.setAttribute('aria-invalid', 'true'); else input.removeAttribute('aria-invalid');
    const nativeLabel = ref.current.querySelector('label'); if (nativeLabel) nativeLabel.htmlFor = fieldId;
    const start = () => { composing.current = true; };
    const end = event => { composing.current = false; const next = event.target.value; setDraft(next); submit(next); };
    input.addEventListener('compositionstart', start); input.addEventListener('compositionend', end);
    return () => { input.removeEventListener('compositionstart', start); input.removeEventListener('compositionend', end); };
  });
  const Component = rows ? TextArea : TextInput;
  return <div ref={ref} className={`comparison-kit-field ${className}`}><Component value={draft} label={label} caption={caption} placeholder={placeholder} disabled={disabled} rows={rows} size="sm" onChange={next => { if (disabled) return; setDraft(next); if (!composing.current) submit(next); }} /></div>;
}
function CompareIcon() { return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" aria-hidden="true"><path d="M3 4h7v16H3zM14 4h7v16h-7zM6 8h1M6 12h1M6 16h1M17 8h1M17 12h1M17 16h1" /></svg>; }
function Header({ title, subtitle, busy, onClose }) { return <header className="comparison-header"><CompareIcon /><div><Caption>{subtitle}</Caption><Heading level={2}><span id="sourceComparisonTitle">{title}</span></Heading></div><Button size="sm" variant="ghost" disabled={busy} aria-label={t('关闭比较，保留草稿', 'Close comparison and retain draft')} onClick={onClose}>✕</Button></header>; }
function ExcerptChoice({ source, status, busy, onApply }) {
  const [open, setOpen] = useState(false), [value, setValue] = useState(source.excerpt);
  if (!status.available || status.redacted) return null;
  if (!open) return <Button size="sm" variant="ghost" disabled={busy || status.stale} onClick={() => { setValue(source.excerpt); setOpen(true); }}>{t('选择摘录', 'Choose excerpt')}</Button>;
  return <div className="comparison-excerpt-choice"><ComparisonField value={value} maxLength={6000} rows={5} disabled={busy} label={t('用于比较的原文片段', 'Source passage to compare')} ariaLabel={t(`${source.title} 的待选原文`, `Excerpt selection for ${source.title}`)} onChange={setValue} /><small>{t('复制来源中的连续段落，最多 6,000 字符。必须与保存的原文完全一致；改写内容请记入个人判断。', 'Copy a continuous passage, up to 6,000 characters. It must match the saved source exactly; put paraphrases in your judgment.')}</small><div className="comparison-excerpt-choice-actions"><Button size="sm" variant="ghost" disabled={busy} onClick={() => setOpen(false)}>{t('取消', 'Cancel')}</Button><Button size="sm" variant="secondary" disabled={busy || !value.trim() || status.stale} onClick={() => { if (onApply(source.key, value)) setOpen(false); }}>{t('使用这段原文', 'Use this passage')}</Button></div></div>;
}
export function ComparisonPicker({ items = [], count, selected = [], query, page, pages, saved = [], error, initialMode, mode: requestedMode = 'comparison', draftPersistence, onRetryDraft, onDiscard, onQuery, onPage, onSelect, onStart, onReopen, onClose }) {
  const [mode, setMode] = useState((initialMode || requestedMode) === 'research' ? 'research' : 'comparison');
  const [confirmDiscard, setConfirmDiscard] = useState(false);
  const researchMode = mode === 'research';
  const privateBlocked = draftPersistence?.blocked === 'private';
  const readUnavailable = draftPersistence?.state === 'unavailable' && !privateBlocked;
  const discardControls = confirmDiscard && privateBlocked ? <div className="comparison-discard-confirmation" role="alertdialog" aria-labelledby="comparisonPickerDiscardTitle" aria-describedby="comparisonPickerDiscardDescription">
    <div><strong id="comparisonPickerDiscardTitle">{t('清除无法读取的本机草稿？', 'Clear the unreadable local draft?')}</strong><p id="comparisonPickerDiscardDescription">{t('清除只会删除本机保存的草稿快照，不会读取或显示其中内容。之后可重新选择来源开始。', 'This only clears the local draft snapshot. Its contents will not be read or shown. You can then select sources and start again.')}</p></div>
    <div><Button size="sm" variant="ghost" onClick={() => setConfirmDiscard(false)}>{t('取消', 'Cancel')}</Button><Button size="sm" variant="danger" onClick={() => { setConfirmDiscard(false); onDiscard?.(); }}>{t('确认清除本机草稿', 'Clear local draft')}</Button></div>
  </div> : null;
  return <section className="comparison-picker"><Header title={researchMode ? t('带着问题看资料', 'Read with a research question') : t('把来源放在一起看', 'Compare sources side by side')} subtitle={t('来源工作台', 'SOURCE WORKSPACE')} onClose={onClose} />
    <div className="comparison-picker-modes"><KitTabs label={t('工作方式', 'Workflow')} value={mode} onChange={setMode} options={[{ value: 'comparison', label: t('并排比较', 'Compare'), id: 'comparisonModeTab', controls: 'comparisonPickerContent' }, { value: 'research', label: t('研究问题', 'Research question'), id: 'researchModeTab', controls: 'comparisonPickerContent' }]} /></div>
    <div id="comparisonPickerContent" role="tabpanel" aria-labelledby={researchMode ? 'researchModeTab' : 'comparisonModeTab'}><p className="comparison-intro">{researchMode ? t('选择 2–4 个来源，围绕一个问题记录支持、反例与背景证据，为每条结论关联依据，保存到科研 Wiki。', 'Choose 2–4 sources. Collect supporting, opposing, and background evidence for one question, link each claim to its evidence, and save to Research Wiki.') : t('选择 2–4 篇笔记、资料或论文。并排查看已保存内容，记录依据、判断和取舍。', 'Choose 2–4 notes, materials, or papers. Review saved content side by side and record evidence, judgments, and a decision.')}</p></div>
    {!privateBlocked && draftPersistence?.state && !['idle', 'unavailable'].includes(draftPersistence.state) && <DraftPersistenceNotice draftPersistence={draftPersistence} onRetryDraft={onRetryDraft} />}
    {privateBlocked && <div className="comparison-private-draft-block" role="alert"><AlertBanner variant="warning" title={t('本机草稿包含已设为私密的来源', 'The local draft includes a source that is now private')} description={t('为保护隐私，草稿内容不会显示，也不能开始新比较或研究以覆盖它。重新开放该来源，或清除本机草稿快照后继续。', 'To protect privacy, the draft is hidden and cannot be overwritten by starting a new comparison or research. Restore access to the source, or clear the local draft snapshot to continue.')} /><div className="comparison-private-actions">{onRetryDraft && <Button size="sm" variant="secondary" disabled={draftPersistence?.blocked === true} onClick={onRetryDraft}>{t('重新检查访问', 'Check access again')}</Button>}{onDiscard && <Button size="sm" variant="ghost" onClick={() => setConfirmDiscard(true)}>{t('清除本机草稿', 'Clear local draft')}</Button>}</div></div>}
    {readUnavailable && <div className="comparison-private-draft-block" role="alert"><AlertBanner variant="warning" title={t('暂时无法读取本机草稿', 'Could not read the local draft')} description={draftPersistence?.message || t('内存中的当前输入仍保留。重新检查保存状态后，才能安全清除或替换本机草稿。', 'Your in-memory input is kept. Check the save state again before clearing or replacing the local draft.')} />{onRetryDraft && <Button size="sm" variant="secondary" disabled={draftPersistence?.blocked === true} onClick={onRetryDraft}>{t('重新检查', 'Check again')}</Button>}</div>}
    {discardControls}
    <div className="comparison-picker-search"><KitSearchInput value={query} label={t('查找来源', 'Find sources')} attributes={{ id: 'comparisonSourceSearch' }} placeholder={t('搜索标题、项目或 DOI', 'Search title, project, or DOI')} onChange={onQuery} /></div>
    {!!saved.length && <details className="comparison-saved"><summary>{t('继续已保存的比较与研究', 'Continue saved comparisons and research')} <Badge>{saved.length}</Badge></summary>{saved.map(note => <Button key={note.id} size="sm" variant="ghost" onClick={() => onReopen(note.id)}>{note.title}</Button>)}</details>}
    <div className="comparison-picker-list" role="group" aria-label={t('可比较来源', 'Available sources')}>{items.length ? items.map(item => <div key={item.key} className={`comparison-picker-row ${selected.includes(item.key) ? 'is-selected' : ''}`}><KitCheckbox checked={selected.includes(item.key)} disabled={!selected.includes(item.key) && selected.length >= 4} label={item.title} description={`${typeName(item.kind)}${item.projectName ? ` · ${item.projectName}` : ''}`} onChange={() => onSelect(item)} /></div>) : <EmptyState title={t('没有匹配来源', 'No matching sources')} description={t('仅显示可访问的普通笔记、资料和论文。', 'Available ordinary notes, materials, and papers appear here.')} />}</div>
    {error && <div role="alert" className="comparison-error"><AlertBanner variant="danger" title={t('暂时无法开始', 'Cannot start yet')} description={error} /></div>}<footer className="comparison-picker-footer"><div><Button size="sm" variant="ghost" disabled={!page} aria-label={t('上一页来源', 'Previous sources')} onClick={() => onPage(page - 1)}>←</Button><span>{page + 1} / {pages} · {count} {t('项', 'items')}</span><Button size="sm" variant="ghost" disabled={page + 1 >= pages} aria-label={t('下一页来源', 'Next sources')} onClick={() => onPage(page + 1)}>→</Button></div><Button id="comparisonStart" size="sm" variant="accent" disabled={privateBlocked || readUnavailable || selected.length < 2 || selected.length > 4} onClick={() => onStart(mode)}>{researchMode ? t('开始研究', 'Start research') : t('开始比较', 'Start comparison')} · {selected.length} / 4</Button></footer>
  </section>;
}
function SourceCard({ source, index, status = {}, researchMode, busy, onSource, onRefresh, onSelectExcerpt }) {
  const accessible = status.available && !status.redacted, metadata = accessible ? source.metadata || {} : {}, title = sourceTitle(source, status);
  return <div className="comparison-source" data-comparison-source={source.key}><div className="comparison-source-eyebrow"><span>{String.fromCharCode(65 + index)} · {typeName(source.kind)}</span><Badge variant={status.stale || !status.available ? 'warning' : 'default'}>{!status.available ? t('不可用', 'Unavailable') : status.stale ? t('有新版本', 'Changed') : t('已冻结', 'Frozen')}</Badge></div><h3 title={title}>{title}</h3>
    {!!(metadata.year || metadata.venue) && <p className="comparison-source-meta">{[metadata.year, metadata.venue].filter(Boolean).join(' · ')}</p>}{!!metadata.authors?.length && <p className="comparison-source-meta">{metadata.authors.join(', ')}</p>}{!!metadata.doi && <p className="comparison-source-meta">DOI: {metadata.doi}</p>}
    {accessible && <details className="comparison-excerpt" open={!researchMode}><summary>{t('来源摘录', 'Source excerpt')} <span>{source.excerpt.length} / {source.totalCharacters}</span></summary><small>{excerptName(source.excerptLabel)}{source.truncated ? t(` · 原文 ${source.excerptOffset || 0}–${(source.excerptOffset || 0) + source.excerpt.length} 字符`, ` · Characters ${source.excerptOffset || 0}–${(source.excerptOffset || 0) + source.excerpt.length}`) : ''}</small><pre tabIndex={0} aria-label={t(`${title} 的冻结摘录`, `Frozen excerpt from ${title}`)}>{source.excerpt || t('没有可用文本。未读取或推断文件正文。', 'No text is available. File contents have not been inferred.')}</pre></details>}
    {status.message && <p className="comparison-source-warning" role="status">{status.message}</p>}<div className="comparison-source-actions"><Button size="sm" variant="ghost" disabled={busy || !accessible || status.stale} onClick={() => onSource(source.key)}>{t('打开来源', 'Open source')} ↗</Button><Button size="sm" variant="ghost" disabled={busy || !accessible} onClick={() => onRefresh(source.key)}>{t('刷新摘录', 'Refresh excerpt')}</Button>{accessible && <ExcerptChoice source={source} status={status} busy={busy} onApply={onSelectExcerpt} />}</div></div>;
}
function EvidenceCell({ row, source, sourceIndex, status, evidence, researchMode, busy, onCell, onReview, onSource }) {
  const cell = row.cells[source.key] || {}, accessible = status?.available && !status?.redacted, title = sourceTitle(source, status), quote = accessible ? cell.quote || '' : '', invalid = !!quote.trim() && !source.excerpt.includes(quote.trim());
  return <div className="comparison-cell" data-comparison-cell={source.key} data-evidence-id={evidence?.id}><h4 className="comparison-mobile-source">{String.fromCharCode(65 + sourceIndex)} · {title}</h4>
    {!accessible ? <p className="comparison-source-warning">{t('来源不可用，已隐藏摘录和判断。恢复访问后可以继续。', 'This source is unavailable. Excerpts and judgments are hidden until access is restored.')}</p> : <>
      <ComparisonField className="comparison-evidence" label={t('来源证据', 'Source evidence')} caption={t('原文连续片段 · 最多 1,200 字符', 'Exact passage · up to 1,200 characters')} value={quote} maxLength={1200} rows={3} disabled={busy} ariaLabel={t(`${row.label}：${title} 的证据`, `${row.label}: evidence from ${title}`)} invalid={invalid} placeholder={t('从来源摘录复制相关原文…', 'Copy relevant text from the source excerpt…')} onChange={value => onCell(row.id, source.key, 'quote', value)} />
      {invalid && <p className="comparison-cell-error">{t('不在当前冻结摘录中，请核对；概括应写在下方。', 'Not in the frozen excerpt. Review the quote; summaries belong below.')}</p>}
      {researchMode && <div className="comparison-relation"><span>{t('相对研究问题', 'Relation to your question')}</span><KitSelect id={`comparisonRelation-${row.id}-${sourceIndex}`} value={cell.relation || 'unclassified'} options={relationOptions()} label={t(`${row.label}：${title} 与问题的关系`, `${row.label}: how ${title} relates to the question`)} disabled={busy} onChange={value => onCell(row.id, source.key, 'relation', value)} /></div>}
      {researchMode ? <details className="comparison-interpretation"><summary>{t('补充你的解读', 'Add your interpretation')}{cell.judgment ? <Badge>{t('已填写', 'Added')}</Badge> : null}</summary><ComparisonField className="comparison-judgment" label={t('个人判断', 'Your judgment')} value={cell.judgment || ''} maxLength={1600} rows={3} disabled={busy} ariaLabel={t(`${row.label}：对 ${title} 的判断`, `${row.label}: your judgment of ${title}`)} placeholder={t('适用条件、局限，或为什么它与问题有关…', 'Conditions, limitations, or why it matters to the question…')} onChange={value => onCell(row.id, source.key, 'judgment', value)} /></details> : <ComparisonField className="comparison-judgment" label={t('个人判断', 'Your judgment')} caption={t('由你填写', 'Written by you')} value={cell.judgment || ''} maxLength={1600} rows={3} disabled={busy} ariaLabel={t(`${row.label}：对 ${title} 的判断`, `${row.label}: your judgment of ${title}`)} placeholder={t('它说明了什么，对当前目标有何帮助或局限…', 'What it means, and its value or limits for your goal…')} onChange={value => onCell(row.id, source.key, 'judgment', value)} />}
      {researchMode && <div className="comparison-review"><span className="comparison-evidence-ref">{evidence?.referenceLabel}</span><StatusBadge status={evidence?.confirmed ? 'online' : 'pending'}>{evidenceName(evidence)}</StatusBadge><div><Button size="sm" variant="ghost" disabled={busy || !evidence?.canOpen} onClick={() => onSource(source.key, evidence?.id)}>{t('定位原文', 'Locate excerpt')} ↗</Button><Button id={`comparisonReview-${row.id}-${sourceIndex}`} size="sm" variant="secondary" disabled={busy || !evidence?.canReview || evidence?.confirmed} onClick={() => onReview(row.id, source.key)}>{evidence?.confirmed ? t('已复核', 'Reviewed') : t('我已复核', 'I reviewed this')}</Button></div></div>}
    </>}
  </div>;
}
function ResearchQuestion({ data, research, busy, onChange }) {
  return <section className="comparison-research-question" aria-labelledby="comparisonQuestionHeading"><Card padding={20} style={{ background: 'var(--panel)', boxShadow: 'none', border: '1px solid var(--line)' }}><div className="comparison-section-heading"><div><Caption>{t('01 · 明确问题', '01 · DEFINE THE QUESTION')}</Caption><Heading level={3}><span id="comparisonQuestionHeading">{t('这次想弄清什么？', 'What do you want to find out?')}</span></Heading></div><StatusBadge status={data.researchStatus === 'ready' && research?.ready ? 'online' : 'pending'}>{research?.needsReview ? t('需要复核', 'Review needed') : statusName(research?.effectiveStatus || data.researchStatus)}</StatusBadge></div>
    <ComparisonField id="comparisonQuestion" label={t('研究问题', 'Research question')} value={data.question || ''} maxLength={2000} rows={2} disabled={busy} placeholder={t('把问题写具体，后面的支持与反例都围绕它展开。', 'Be specific. Supporting and opposing evidence will refer to this question.')} onChange={value => onChange('question', value)} />
    <details className="comparison-scope"><summary>{t('研究范围与边界', 'Scope and boundaries')}{data.scope ? <Badge>{t('已填写', 'Added')}</Badge> : null}</summary><ComparisonField id="comparisonScope" label={t('适用范围', 'Scope')} value={data.scope || ''} maxLength={2000} rows={2} disabled={busy} placeholder={t('限定对象、场景、时间或评价条件。', 'Specify the population, setting, time, or evaluation conditions.')} onChange={value => onChange('scope', value)} /></details></Card></section>;
}
function ResearchClaims({ data, research = {}, busy, onChange, onClaim, onAddClaim, onRemoveClaim }) {
  const evidence = research.evidence || [], claimViews = research.claims || [], readiness = research.readinessReasons || research.problems || [];
  return <section className="comparison-research-claims" aria-labelledby="comparisonClaimsHeading"><div className="comparison-section-heading"><div><Caption>{t('03 · 写下结论', '03 · FORM YOUR CLAIMS')}</Caption><Heading level={3}><span id="comparisonClaimsHeading">{t('每条结论，都能找到依据', 'Connect every claim to its evidence')}</span></Heading></div><Badge>{(data.claims || []).length} / 16</Badge></div><p className="comparison-section-description">{t('结论由你整理。勾选证据只建立关联；“已复核”表示你确认了原文与分类，不表示 AI 已验证结论。', 'You write the claims. Evidence links record your reasoning; “reviewed” means you checked the excerpt and relation, not that AI verified the claim.')}</p>
    <div className="comparison-claims-list">{(data.claims || []).map((claim, index) => {
      const view = claimViews.find(item => item.id === claim.id), ids = claim.evidenceIds || [], options = evidence.filter(item => item.quote?.trim() || ids.includes(item.id)), missing = ids.filter(id => !evidence.some(item => item.id === id));
      return <div key={claim.id} data-comparison-claim={claim.id} className="comparison-claim"><Card padding={18} style={{ background: 'var(--panel)', boxShadow: 'none', border: '1px solid var(--line)' }}><div className="comparison-claim-heading"><strong>{t(`结论 ${index + 1}`, `Claim ${index + 1}`)}</strong><Button size="sm" variant="ghost" disabled={busy} aria-label={t(`移除结论 ${index + 1}`, `Remove claim ${index + 1}`)} onClick={() => onRemoveClaim(claim.id)}>{t('移除', 'Remove')}</Button></div><ComparisonField id={`comparisonClaim-${claim.id}`} label={t('结论陈述', 'Claim')} value={claim.text || ''} maxLength={1600} rows={2} disabled={busy} ariaLabel={t(`结论 ${index + 1} 的陈述`, `Claim ${index + 1} statement`)} placeholder={t('基于当前资料，可以得出的判断是…', 'Based on the current sources…')} onChange={value => onClaim(claim.id, 'text', value)} />
        <details className="comparison-claim-evidence" open><summary>{t('关联依据', 'Link evidence')}<Badge>{ids.length}</Badge></summary>{options.length ? options.map((item, evidenceIndex) => { const selected = ids.includes(item.id), disabled = busy || (!selected && !item.confirmed); const label = `${item.referenceLabel || ''} · ${item.label || t('证据', 'Evidence')} · ${item.sourceTitle || t('来源不可用', 'Source unavailable')} · ${relationName(item.relation)}`; return <div className="comparison-claim-option" key={item.id} data-evidence-choice={item.id}><KitCheckbox id={`comparisonClaimEvidence-${claim.id}-${evidenceIndex}`} label={label} description={item.available ? item.quote : t('来源不可用；可移除此关联。', 'Source unavailable; this link can be removed.')} checked={selected} disabled={disabled} onChange={checked => onClaim(claim.id, 'evidenceIds', checked ? [...ids, item.id] : ids.filter(id => id !== item.id))} /><span className="comparison-claim-option-status">{evidenceName(item)}</span></div>; }) : <p className="comparison-section-description">{t('先在上方添加原文、标注关系并复核，再为这条结论选择依据。', 'Add, classify, and review an excerpt above, then select evidence for this claim.')}</p>}{missing.map((id, missingIndex) => <div className="comparison-claim-option" key={id}><KitCheckbox checked label={t(`已移除的证据 ${missingIndex + 1}`, `Removed evidence ${missingIndex + 1}`)} description={t('原维度或来源已移除，请取消关联。', 'The original criterion or source was removed. Unlink this evidence.')} disabled={busy} onChange={() => onClaim(claim.id, 'evidenceIds', ids.filter(item => item !== id))} /></div>)}</details>
        {!!view?.issues?.length && <p className="comparison-cell-error" role="status">{view.issues.join(t('；', '; '))}</p>}</Card></div>;
    })}</div><Button size="sm" variant="secondary" disabled={busy || (data.claims || []).length >= 16} onClick={onAddClaim}>＋ {t('添加结论', 'Add claim')}</Button>
    <div className="comparison-research-outcome"><ComparisonField id="comparisonOpenQuestions" label={t('仍缺什么证据，下一步做什么？', 'What evidence is missing, and what comes next?')} value={data.openQuestions || ''} maxLength={6000} rows={3} disabled={busy} placeholder={t('记录分歧、未覆盖的情形，或需要补充的实验与材料。', 'Record disagreements, uncovered cases, or experiments and sources still needed.')} onChange={value => onChange('openQuestions', value)} /><div className="comparison-research-status"><span>{t('保存状态', 'Research status')}</span><KitSelect id="comparisonResearchStatus" label={t('研究保存状态', 'Research status')} value={data.researchStatus || 'draft'} disabled={busy} onChange={value => onChange('researchStatus', value)} options={[{ value: 'draft', label: statusName('draft') }, { value: 'insufficient', label: statusName('insufficient') }, { value: 'ready', label: statusName('ready'), disabled: !research.ready }]} /><small>{t('草稿和证据不足可先保存；已整理需要每条结论关联当前已复核的证据。', 'Save drafts or insufficient evidence now. Organized claims need current, reviewed evidence links.')}</small></div></div>
    {!!readiness.length && <details className="comparison-readiness" open={data.researchStatus === 'ready'}><summary>{t('整理前还需检查', 'Before marking as organized')} <Badge>{readiness.length}</Badge></summary><ul>{readiness.map((reason, index) => <li key={index}>{reason}</li>)}</ul></details>}
  </section>;
}
function DraftPersistenceNotice({ draftPersistence, onRetryDraft, privateSource = false, busy }) {
  if (!draftPersistence && !privateSource) return null;
  const state = privateSource ? 'error' : draftPersistence?.state;
  if (!state || state === 'idle') return null;
  const labels = {
    saving: t('正在保存本机草稿', 'Saving local draft'),
    saved: t('本机草稿已保存', 'Local draft saved'),
    error: t('本机草稿未保存', 'Local draft was not saved'),
    conflict: t('存在另一个窗口的草稿', 'A draft exists in another window'),
    unavailable: t('本机草稿暂不可用', 'Local draft is unavailable'),
  };
  const safeMessage = privateSource
    ? t('来源已设为私密，本机草稿自动保存已暂停；正文不会在此显示。', 'A source is now private, so local draft saving is paused. The content is hidden here.')
    : state === 'saved'
      ? t('草稿已保存在本机，重新打开应用可继续；保存到 Wiki 后才成为正式笔记。', 'Draft saved on this device. Reopen the app to continue; save to Wiki to make it a note.')
      : state === 'conflict'
        ? t('当前输入已保留。可以保存为笔记，或放弃当前编辑并载入已保存的草稿。', 'Your current input is kept. Save it as a note, or discard these edits and load the saved draft.')
        : String(draftPersistence?.message || (state === 'saving'
          ? t('正在将更改保存到本机。', 'Saving your changes on this device.')
          : state === 'unavailable'
            ? t('本机草稿保存不可用；请先复制重要内容，再保存为笔记。', 'Local draft saving is unavailable. Copy important content before saving it as a note.')
            : t('本机草稿保存失败；当前输入仍保留在窗口中。', 'The local draft could not be saved. Your current input remains in this window.')));
  const isError = ['error', 'conflict', 'unavailable'].includes(state);
  const updatedAt = !privateSource && state === 'saved' && draftPersistence?.updatedAt ? new Date(draftPersistence.updatedAt) : null;
  const timeLabel = updatedAt && Number.isFinite(updatedAt.getTime())
    ? t(`最近保存：${updatedAt.toLocaleString('zh-CN')}`, `Saved ${updatedAt.toLocaleString()}`)
    : '';
  return <section className={`comparison-draft-persistence is-${state}`} data-draft-state={state} aria-live="polite" aria-atomic="true">
    {isError ? <div className="comparison-draft-alert"><AlertBanner variant="danger" title={labels[state] || labels.error} description={safeMessage} /></div> : <div className="comparison-draft-persistence-line"><StatusBadge status={state === 'saved' ? 'online' : state === 'saving' ? 'accent' : 'pending'} pulse={state === 'saving'}>{labels[state] || labels.saving}</StatusBadge><Caption>{safeMessage}</Caption></div>}
    {timeLabel && <span className="comparison-draft-persistence-time"><Caption>{timeLabel}{draftPersistence?.recovered ? t(' · 已从本机恢复', ' · Recovered from this device') : ''}</Caption></span>}
    {!privateSource && isError && onRetryDraft && <Button size="sm" variant="secondary" disabled={busy || !!draftPersistence?.blocked} onClick={onRetryDraft}>{t('重试保存草稿', 'Retry local save')}</Button>}
    {!privateSource && draftPersistence?.blocked && <Caption>{t('当前操作完成后可重试。', 'Retry after the current operation finishes.')}</Caption>}
  </section>;
}
export function SourceComparisonSurface({ data, statuses = {}, research, busy, changed, noteId, externalChanged, error, notice, projects = [], draftPersistence, onRetryDraft, onChange, onCriterion, onCell, onAddCriterion, onRemoveCriterion, onRefresh, onSelectExcerpt, onSource, onReview, onClaim, onAddClaim, onRemoveClaim, onSave, onSaveAs, onOpenNote, onNew, onDiscard, onClose }) {
  const [confirmDiscard, setConfirmDiscard] = useState(false);
  const privateSource = Object.values(statuses).some(status => status.private);
  const draftUnreadable = draftPersistence?.state === 'unavailable' && draftPersistence?.blocked !== 'private';
  const knownLocalDraft = !!draftPersistence && ['saving', 'saved', 'error', 'conflict'].includes(draftPersistence.state);
  const canDiscard = typeof onDiscard === 'function' && !draftUnreadable && (!!changed || knownLocalDraft || draftPersistence?.blocked === 'private');
  const discardOrigin = useRef(null), discardPrompt = useRef(null);
  const requestDiscard = () => { if (!busy && canDiscard) { discardOrigin.current = document.activeElement; setConfirmDiscard(true); } };
  const cancelDiscard = () => { setConfirmDiscard(false); discardOrigin.current?.focus?.({ preventScroll: true }); };
  useLayoutEffect(() => { if (confirmDiscard) discardPrompt.current?.querySelector('button')?.focus({ preventScroll: true }); }, [confirmDiscard]);
  const discardDraft = () => {
    if (busy || !canDiscard) return;
    setConfirmDiscard(false);
    onDiscard();
  };
  const discardControls = canDiscard && confirmDiscard ? <div ref={discardPrompt} onKeyDown={event => { if (event.key === 'Escape') { event.stopPropagation(); event.preventDefault(); cancelDiscard(); } }} className="comparison-discard-confirmation" role="alertdialog" aria-labelledby="comparisonDiscardTitle" aria-describedby="comparisonDiscardDescription">
    <div><strong id="comparisonDiscardTitle">{draftPersistence?.state === 'conflict' ? t('载入已保存的本机草稿？', 'Load the saved local draft?') : t('放弃本机草稿？', 'Discard the local draft?')}</strong><p id="comparisonDiscardDescription">{draftPersistence?.state === 'conflict' ? t('这会放弃当前窗口的编辑并载入已保存草稿；不会删除已保存草稿。', 'This discards edits in the current window and loads the saved draft. The saved draft is kept.') : t('这会删除已保存的本机草稿，并放弃当前编辑。此操作无法撤销。', 'This deletes the saved local draft and discards current edits. This cannot be undone.')}</p></div>
    <div><Button size="sm" variant="ghost" disabled={busy} onClick={cancelDiscard}>{t('继续编辑', 'Keep editing')}</Button><Button size="sm" variant="danger" disabled={busy} onClick={discardDraft}>{draftPersistence?.state === 'conflict' ? t('确认放弃当前编辑并载入已保存草稿', 'Discard current edits and load saved draft') : t('确认放弃本机草稿', 'Discard local draft')}</Button></div>
  </div> : null;
  if (privateSource) return <section className="source-comparison-surface"><Header title={t('来源比较', 'Source comparison')} subtitle={t('来源访问已变化', 'SOURCE ACCESS CHANGED')} busy={busy} onClose={onClose} /><EmptyState title={t('比较包含已设为私密的来源', 'A source in this comparison is now private')} description={t('来源摘录、证据、标题与判断暂不显示，也不能继续保存。关闭不会修改已有笔记。', 'Source excerpts, evidence, titles, and judgments are hidden, and saving is unavailable. Closing does not alter existing notes.')} action={<div className="comparison-private-actions"><Button size="sm" variant="secondary" disabled={busy} onClick={onClose}>{t('关闭', 'Close')}</Button>{canDiscard && <Button size="sm" variant="ghost" disabled={busy} onClick={requestDiscard}>{t('放弃本机草稿', 'Discard local draft')}</Button>}</div>} /><DraftPersistenceNotice draftPersistence={draftPersistence} privateSource busy={busy} />{discardControls}</section>;
  const researchMode = data.version === 2 && data.mode === 'research';
  const unavailable = data.sources.some(source => !statuses[source.key]?.available), stale = data.sources.some(source => statuses[source.key]?.stale), readyBlocked = researchMode && data.researchStatus === 'ready' && !research?.ready;
  const saveBlocked = unavailable || (!researchMode && stale) || readyBlocked || (researchMode && !!research?.blocked);
  const draftFallback = draftPersistence
    ? (researchMode ? t('本机草稿状态见上方；保存到科研 Wiki 后才成为正式笔记。', 'See the local draft status above. Save to Research Wiki to create a note.') : t('本机草稿状态见上方；保存后才会成为正式笔记。', 'See the local draft status above. Save to create a note.'))
    : t('关闭保留本次窗口内草稿；刷新或退出应用后未保存内容会丢失。', 'Closing retains this draft in the current window. Unsaved edits are lost when the app exits or reloads.');
  const sourceProps = { researchMode, busy, onSource, onRefresh, onSelectExcerpt };
  return <section className={`source-comparison-surface ${researchMode ? 'is-research' : ''}`} aria-busy={busy || undefined}><Header title={researchMode ? t('问题与证据', 'Question and evidence') : t('来源比较', 'Source comparison')} subtitle={researchMode ? t('研究工作台 · 保存到科研 Wiki', 'RESEARCH WORKSPACE · RESEARCH WIKI') : t('依据并排 · 判断分开', 'EVIDENCE & YOUR JUDGMENTS')} busy={busy} onClose={onClose} />
    <DraftPersistenceNotice draftPersistence={draftPersistence} onRetryDraft={onRetryDraft} busy={busy} />
    <div className="comparison-document-fields"><ComparisonField id="comparisonTitle" label={researchMode ? t('研究标题', 'Research title') : t('比较标题', 'Comparison title')} value={data.title} maxLength={240} disabled={busy} onChange={value => onChange('title', value)} /><div className="comparison-project-field"><span>{researchMode ? t('科研项目', 'Research project') : t('保存到项目', 'Save to project')}</span><KitSelect id="comparisonProject" value={data.projectId || ''} disabled={busy} label={researchMode ? t('保存到科研项目', 'Save to research project') : t('保存到项目', 'Save to project')} onChange={value => onChange('projectId', value || null)} options={[{ value: '', label: researchMode ? t('科研 Wiki · 未归属项目', 'Research Wiki · no project') : t('不指定项目', 'No project') }, ...projects.map(project => ({ value: project.id, label: project.name }))]} /></div></div>
    <div className="comparison-workspace">
      {researchMode && <ResearchQuestion data={data} research={research} busy={busy} onChange={onChange} />}
      {researchMode && <div className="comparison-evidence-heading"><div><Caption>{t('02 · 核对证据', '02 · REVIEW THE EVIDENCE')}</Caption><Heading level={3}>{t('原文、关系与解读分开记录', 'Separate excerpts, relations, and interpretation')}</Heading></div><Badge>{research?.counts?.confirmed || 0} / {research?.counts?.quoted || 0} {t('已复核', 'reviewed')}</Badge><p>{t('支持、反例和背景都相对上方问题。来源、问题或解读变化后，需要重新复核；刷新摘录会保留你的输入。', 'Relations refer to the question above. Source, question, or interpretation changes require a new review. Refreshing keeps your input.')}</p></div>}
      <div className="comparison-table" style={{ '--comparison-columns': data.sources.length }}><section className="comparison-source-row"><div className="comparison-row-label"><strong>{t('来源事实', 'Source facts')}</strong><p>{t('冻结摘录与已保存元数据。不会自动替你比较或判断。', 'Frozen excerpts and saved metadata. No automatic judgments are added.')}</p></div>{data.sources.map((source, index) => <SourceCard key={source.key} source={source} index={index} status={statuses[source.key]} {...sourceProps} />)}</section>
        {data.criteria.map((row, rowIndex) => <section className="comparison-criterion-row" key={row.id} data-comparison-criterion={row.id}><div className="comparison-row-label"><ComparisonField label={researchMode ? t(`证据组 ${rowIndex + 1}`, `Evidence group ${rowIndex + 1}`) : t(`维度 ${rowIndex + 1}`, `Criterion ${rowIndex + 1}`)} value={row.label} maxLength={100} disabled={busy} ariaLabel={t(`比较维度 ${rowIndex + 1}`, `Comparison criterion ${rowIndex + 1}`)} onChange={value => onCriterion(row.id, value)} /><Button size="sm" variant="ghost" disabled={busy || data.criteria.length === 1} onClick={() => onRemoveCriterion(row.id)}>{researchMode ? t('移除此组', 'Remove group') : t('移除此维度', 'Remove criterion')}</Button></div>{data.sources.map((source, sourceIndex) => <EvidenceCell key={source.key} row={row} source={source} sourceIndex={sourceIndex} status={statuses[source.key]} evidence={research?.evidence?.find(item => item.rowId === row.id && item.sourceKey === source.key)} researchMode={researchMode} busy={busy} onCell={onCell} onReview={onReview} onSource={onSource} />)}</section>)}
      </div><div className="comparison-add-criterion"><Button size="sm" variant="ghost" disabled={busy || data.criteria.length >= 8} onClick={onAddCriterion}>＋ {researchMode ? t('添加证据组', 'Add evidence group') : t('添加比较维度', 'Add criterion')}</Button><span>{data.criteria.length} / 8</span></div>
      {researchMode ? <ResearchClaims data={data} research={research} busy={busy} onChange={onChange} onClaim={onClaim} onAddClaim={onAddClaim} onRemoveClaim={onRemoveClaim} /> : <section className="comparison-decision"><div><Caption>{t('你的取舍', 'YOUR DECISION')}</Caption><h3>{t('选择与结论', 'Choice and conclusion')}</h3><p>{t('可以暂不做选择。结论保留你的判断，不会被标记为已核验事实。', 'You can leave the choice open. Your conclusion remains a judgment, not a verified fact.')}</p></div><div className="comparison-decision-fields"><KitRadioGroup label={t('倾向选择', 'Preferred option')} value={data.selectedKey || ''} disabled={busy} options={[{ value: '', label: t('尚未选择', 'Undecided') }, ...data.sources.map((source, index) => ({ value: source.key, label: `${String.fromCharCode(65 + index)} · ${sourceTitle(source, statuses[source.key])}`, disabled: !statuses[source.key]?.available }))]} onChange={value => onChange('selectedKey', value)} /><ComparisonField id="comparisonConclusion" label={t('结论与下一步', 'Conclusion and next steps')} value={data.conclusion} maxLength={6000} rows={4} disabled={busy} placeholder={t('记录选择理由、尚缺的证据，以及下一步需要确认的事项。', 'Record your reasons, missing evidence, and what to check next.')} onChange={value => onChange('conclusion', value)} /></div></section>}
    </div>
    <div className="comparison-save-status" role={error || externalChanged ? 'alert' : 'status'} aria-live="polite">{error || (externalChanged ? t('笔记正文已在别处修改，保存不会覆盖它。可以另存新的比较笔记。', 'The note text was edited elsewhere. Save a new comparison note to keep those edits.') : busy ? t('正在保存，请稍候…', 'Saving…') : notice || (unavailable ? t('部分来源不可用，请恢复访问后再保存。', 'Some sources are unavailable. Restore access before saving.') : stale ? researchMode ? t('来源有变化。可以保存草稿；刷新摘录并重新复核后再标记已整理。', 'Sources changed. You can save a draft; refresh and review evidence before marking as organized.') : t('部分来源已变化或不可用。请先核对来源再保存。', 'Some sources changed. Review them before saving.') : readyBlocked ? t('证据关联需要重新复核，可先改为草稿保存。', 'Evidence links need review. Switch to Draft to save now.') : draftFallback))}</div>
    {discardControls}
    <footer className="comparison-footer"><div><Button size="sm" variant="ghost" disabled={busy} onClick={canDiscard ? requestDiscard : onNew}>{canDiscard ? draftPersistence?.state === 'conflict' ? t('载入已保存草稿', 'Load saved draft') : t('放弃本机草稿', 'Discard local draft') : changed ? t('放弃草稿', 'Discard draft') : researchMode ? t('新建研究', 'New research') : t('新建比较', 'New comparison')}</Button>{noteId && <Button size="sm" variant="ghost" disabled={busy || changed} onClick={onOpenNote}>{researchMode ? t('打开 Wiki 笔记', 'Open Wiki note') : t('打开笔记', 'Open note')} ↗</Button>}</div><div>{noteId && <Button size="sm" variant="secondary" disabled={busy || saveBlocked} onClick={onSaveAs}>{t('另存为新笔记', 'Save as new note')}</Button>}<Button id="comparisonSave" size="sm" variant="accent" loading={busy} disabled={saveBlocked || externalChanged || (!changed && !!noteId)} onClick={onSave}>{researchMode ? noteId ? t('保存研究', 'Save research') : t('保存到科研 Wiki', 'Save to Research Wiki') : noteId ? t('保存比较', 'Save comparison') : t('保存为笔记', 'Save as note')}</Button></div></footer>
  </section>;
}
