import React, { useLayoutEffect, useRef, useState } from 'react';
import { Badge, Button, Card, EmptyState, StatusBadge } from './halaska-kit.jsx';
import { KitSearchInput, KitSelect } from './kit-controls.jsx';
import styles from './history-surfaces.css';
if (!document.getElementById('halaska-history-styles')) {
  const style = document.createElement('style'); style.id = 'halaska-history-styles'; style.textContent = styles; document.head.append(style);
}
const t = (zh, en) => /^en(?:-|$)/i.test(document.documentElement.lang) ? en : zh;
const statuses = () => [ ['all',t('全部状态','All statuses')], ['running',t('执行中','Running')], ['awaiting-approval',t('等待审批','Needs approval')], ['awaiting-save',t('等待保存结果','Awaiting save')], ['completed',t('已完成（含本地）','Completed, including local')], ['failed',t('执行失败 / 未完成','Failed / incomplete')], ['cancelled',t('已停止','Stopped')], ['rejected',t('已拒绝','Rejected')], ['interrupted',t('已中断','Interrupted')] ].map(([value,label]) => ({value,label}));
const stepNames = () => ({ done:t('已完成','Done'), completed:t('已完成','Done'), running:t('进行中','Running'), error:t('失败','Failed'), failed:t('失败','Failed'), pending:t('等待','Pending'), queued:t('等待','Queued'), cancelled:t('已停止','Stopped'), interrupted:t('已中断','Interrupted') });
const stateLabel = value => Object.hasOwn(stepNames(), value) ? stepNames()[value] : value || t('已记录','Recorded');
function Goal({title}) {
  const [expanded,setExpanded]=useState(false), long=title.length>120;
  return <div className="history-kit-goal"><h3 data-user-content className={long&&!expanded?'is-collapsed':undefined}>{title}</h3>{long&&<Button size="sm" variant="ghost" aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)}>{expanded?t('收起目标','Collapse goal'):t('展开完整目标','Show full goal')}</Button>}</div>;
}
function Status({record}) { return <StatusBadge status={record.tone}>{record.label}</StatusBadge>; }
export function RunHistoryToolbar({query='',status='all',total=0,count=0,checkedCount=0,allChecked=false,partlyChecked=false,canSelect=false,busy=false,onQuery,onStatus,onSelectAll,onClear,onDelete,onRefresh,onClose,onCompositionStart,onCompositionEnd}) {
  const checkbox=useRef(null);
  useLayoutEffect(()=>{checkbox.current.indeterminate=partlyChecked;checkbox.current.closest('[data-halaska-root]')?.querySelector('#runHistoryClose')?.classList.add('run-history-close');},[partlyChecked]);
  return <>
    <header className="run-history-header"><div><span className="history-kit-eyebrow">{t('工作记录','WORK LOG')}</span><h2 id="runHistoryTitle">{t('执行历史','Run history')}</h2><p>{t('查看每次执行的过程、结果与原对话。','Review each run, its results, and the original conversation.')}</p></div><div className="run-history-header-actions"><Button size="sm" variant="ghost" disabled={busy} onClick={onRefresh}>{t('刷新','Refresh')}</Button><Button id="runHistoryClose" size="sm" variant="ghost" disabled={busy} aria-label={t('关闭执行历史','Close run history')} onClick={onClose}>×</Button></div></header>
    <div className="run-history-controls"><KitSearchInput value={query} onChange={onQuery} onCompositionStart={onCompositionStart} onCompositionEnd={onCompositionEnd} attributes={{id:'runHistorySearch'}} label={t('搜索执行目标','Search run goals')} placeholder={t('搜索执行目标…','Search run goals…')} disabled={busy}/><KitSelect id="runHistoryStatus" value={status} options={statuses()} onChange={onStatus} label={t('按执行状态筛选','Filter by run status')} disabled={busy}/></div>
    <div className="history-kit-selection"><p className="run-history-count" role="status">{query.trim()||status!=='all'?t(`${count} / ${total} 条记录`,`${count} / ${total} records`):t(`${total} 条记录 · 包含已归档对话`,`${total} records · Archived conversations included`)}</p><div className="run-history-bulk"><label className="run-history-select-all" title={t('选择筛选结果中的全部已结束日志，包括尚未展开的记录','Select all finished records matching these filters, including those not loaded')}><input ref={checkbox} id="runHistorySelectAll" type="checkbox" checked={allChecked} disabled={!canSelect||busy} onChange={event=>onSelectAll(event.target.checked)}/><span>{t('全选筛选结果','Select matching')}</span></label><span className="run-history-selection-count" aria-live="polite">{checkedCount?t(`已选 ${checkedCount} 条`,`${checkedCount} selected`):t('仅清除本机日志，成果保留','Local logs only; results are kept')}</span><Button id="runHistoryClearSelection" size="sm" variant="ghost" disabled={!checkedCount||busy} onClick={onClear}>{t('取消选择','Clear selection')}</Button><Button id="runHistoryDeleteSelected" size="sm" variant="ghost" disabled={!checkedCount||busy} onClick={onDelete}>{checkedCount?t(`删除所选 (${checkedCount})`,`Delete selected (${checkedCount})`):t('删除所选','Delete selected')}</Button></div></div>
  </>;
}
export function RunHistoryList({rows=[],total=0,remaining=0,busy=false,onSelect,onCheck,onMore}) {
  return <div className="history-kit-list-content">
    {!rows.length&&<EmptyState title={total?t('没有匹配记录','No matching records'):t('还没有执行记录','No runs yet')} description={total?t('试试其他关键词或状态。','Try a different keyword or status.'):t('发起一次工作流后，会在这里留下历史。','Your workflow history appears here once a run starts.')}/>}
    {rows.map(row=><div key={row.id} className="run-history-item" data-selected={row.checked}>
      <label className="run-history-select" title={row.canDelete?t('选择这条执行日志','Select this log'):t('执行中、待审批或尚未确认结束的记录不能删除','Active, pending approval, and unconfirmed records cannot be deleted')}><input type="checkbox" data-select-run={row.id} aria-label={t(`选择执行日志：${row.title}`,`Select run log: ${row.title}`)} checked={row.checked} disabled={!row.canDelete||busy} onChange={event=>onCheck(row.id,event.target.checked)}/></label>
      <button type="button" className="run-history-row" data-run-id={row.id} aria-pressed={row.selected} disabled={busy} onClick={()=>onSelect(row.id)}><strong data-user-content>{row.title}</strong><span className="history-kit-row-status"><Status record={row}/>{row.resultCount>0&&<small>{t(`${row.resultCount} 项结果`,`${row.resultCount} results`)}</small>}</span><small data-user-content title={row.original}>{row.original}</small><time>{row.started}</time></button>
    </div>)}
    {remaining>0&&<div className="history-kit-more"><Button size="sm" variant="secondary" disabled={busy} onClick={onMore}>{t(`再显示 ${remaining} 条`,`Show ${remaining} more`)}</Button></div>}
  </div>;
}
function ToolRecord({tool}) {
  return <details className="history-kit-tool" data-tool-id={tool.id}><summary><span data-user-content>{tool.type||t('工具操作','Tool operation')}</span><span>{stateLabel(tool.status)}</span></summary><div className="history-kit-tool-body">{tool.summary&&<p data-user-content>{tool.summary}</p>}{tool.error&&<p className="history-kit-error" data-user-content>{tool.error}</p>}{[['request',t('参数','Arguments')],['result',t('结果','Result')]].map(([key,label])=>tool[key]&&<section key={key}><h5>{label}</h5><pre tabIndex={0} data-user-content>{tool[key]}</pre></section>)}</div></details>;
}
export function RunHistoryDetail({record,missing=false,busy=false,error='',onBack,onOriginal,onDelete,onResult}) {
  if (!record) return <div className="history-kit-detail-empty"><EmptyState title={missing?t('记录已不可用','Record unavailable'):t('每次执行，都有来处','Every run has a record')} description={missing?t('该记录已移入回收站或不再可用。','The record was removed or is no longer available.'):t('选择一条记录，查看目标、过程和可打开的成果。','Select a run to inspect its goal, process, and available results.')}/></div>;
  return <div className="history-kit-detail-content" key={record.id}>
    <div className="run-history-detail-heading"><div className="history-kit-detail-top"><Button size="sm" variant="ghost" disabled={busy} onClick={onBack}>← {t('返回列表','Back to list')}</Button><Status record={record}/></div><Goal title={record.title}/><div className="history-kit-origin"><Button size="sm" variant="secondary" disabled={busy||!record.canOpenOriginal} onClick={onOriginal}>{record.canOpenOriginal?t('打开原对话 ↗','Open conversation ↗'):t('原对话不可直接打开','Original conversation unavailable')}</Button></div></div>
    {(record.error||record.historicalIssue)&&<section className="history-kit-outcome" role="note"><Card padding={14}><h4>{t('执行说明','Run outcome')}</h4><p data-user-content>{record.error}</p>{record.diagnosticDetails?.length>0&&<dl>{record.diagnosticDetails.map((row,index)=><div key={index}><dt>{row.label}</dt><dd data-user-content>{row.value}</dd></div>)}</dl>}{record.hint&&<p className="run-history-muted">{record.hint}</p>}</Card></section>}
    <section className="run-history-section history-kit-results"><h4>{t(`执行结果 · ${record.results.length} 项`,`Results · ${record.results.length}`)}</h4>{!record.results.length?<p className="run-history-muted">{record.status==='awaiting-approval'?t('尚未执行。请回到原对话查看待审批计划。','Not executed. Open the conversation to review the pending plan.'):t('没有写入结果记录；文字回答可在原对话中查看。','No saved result records. Written answers are available in the original conversation.')}</p>:record.results.map(result=><Card key={`${result.index}:${result.type}:${result.id}`} padding={13}><div className="history-kit-result"><Badge>{result.label}</Badge><div className="history-kit-result-copy"><strong data-user-content>{result.title}</strong>{!result.available&&<p>{result.reason}</p>}</div><Button size="sm" variant="secondary" disabled={busy||!result.available} aria-label={t(`打开${result.label}：${result.title}`,`Open ${result.label}: ${result.title}`)} onClick={()=>onResult(result.index)}>{t('打开','Open')} <span aria-hidden="true">↗</span></Button></div></Card>)}</section>
    <details className="history-kit-context" open><summary>{t('执行信息','Run details')}</summary><dl className="run-history-meta">{record.metadata.map(([name,value])=><div key={name}><dt>{name}</dt><dd data-user-content>{String(value)}</dd></div>)}</dl></details>
    <section className="run-history-section history-kit-steps"><h4>{t(`执行步骤 · ${record.steps.length} 项`,`Steps · ${record.steps.length}`)}</h4>{record.steps.length?<ol>{record.steps.map(step=><li key={step.id}><span className="history-kit-step-state">{stateLabel(step.status)}</span><span data-user-content>{step.title}</span></li>)}</ol>:<p className="run-history-muted">{t('这次执行没有记录步骤。','No steps were recorded for this run.')}</p>}</section>
    {record.tools.length>0&&<details className="history-kit-tools"><summary>{t(`工具执行记录 · ${record.tools.length}`,`Tool history · ${record.tools.length}`)}</summary>{record.tools.map(tool=><ToolRecord key={tool.id} tool={tool}/>)}</details>}
    {error&&<p className="history-kit-error" role="alert">{error}</p>}<div className="run-history-detail-actions"><span className="run-history-muted">{t('删除日志会保留对话与成果','Deleting a log keeps its conversation and results')}</span><Button id="runHistoryDeleteOne" size="sm" variant="ghost" disabled={busy||!record.canDelete} onClick={onDelete}>{t('删除这条日志','Delete this log')}</Button></div>
  </div>;
}
